FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/

RUN apt-get update && \
    apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-eng \
    libgl1-mesa-glx \
    libglib2.0-0 \
    poppler-utils \
    wget && \
    mkdir -p /usr/share/tesseract-ocr/4.00/ && \
    ln -s /usr/share/tesseract-ocr/5/tessdata /usr/share/tesseract-ocr/4.00/tessdata && \
    apt-get clean

RUN apt-get update

# Debug Hugging Face Cache Directory
RUN mkdir -p /root/.cache/huggingface/hub && chmod -R 755 /root/.cache/huggingface/hub

COPY requirements.dev.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.dev.txt

RUN pip install --upgrade unstructured[all] onnxruntime onnx

WORKDIR /app

COPY src /app/src

WORKDIR /app/src

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD ["python", "test.py"]
