FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TESSDATA_PREFIX=/usr/local/share/tessdata

RUN apt-get update && \
    apt-get install -y \
    tesseract-ocr \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && apt-get clean

COPY requirements.dev.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.dev.txt

WORKDIR /app

COPY src /app/src

WORKDIR /app/src

CMD ["python3", "test.py"]
