ENVIRONMENT: null

API:
  prefix: "/api/v1"
  upload_pdf: "/upload_pdf"
  chatbot: "/chatbot"

TIMEZONE: Asia/Bangkok

EMBEDDING:
    
PROMPT:
  trigger_words:
    system_prompt: system_prompt
    input_prompt: input_prompt
  content_types:
    - Research
  prompt_files:
    image_summary: prompts/image_summary.txt
    refine_query: prompts/refine_query.txt
    find_titles: prompts/find_titles.txt
    intent_detection: prompts/intent_detection.txt
    chatbot_response: prompts/chatbot_response.txt

REDIS:
  key:
    prefix: MinKhant_
    sufix: _RAG

User_Data_Local:
  user_data_path: tmp

RAG:
  text_split_methods:        # add more to the list if required to split the text in different ways
    - semantic_chunker     # if only one method is required, then replace the method here
  retrieve:
    text_split_methods:
      - semantic_chunker
    retrieve_type: similarity  # "similarity", "mmr", "similarity_score_threshold"