ENVIRONMENT: dev

TIMEZONE: Asia/Bangkok

EMBEDDING:
    
PROMPT_CONFIG:
  trigger_words:
    system_prompt: system_prompt
    input_prompt: input_prompt
  CONTENT_TYPES:
    - Research
  PROMPT_FILES:
    image_summary: prompts/image_summary.txt
    refine_query: prompts/refine_query.txt
    find_titles: find_titles.txt

REDIS:
  key:
    prefix: "MinKhant_"
    sufix: "_RAG"

User_Data_Local:
  user_data_path: "tmp"