ENVIRONMENT: dev

TIMEZONE: Asia/Bangkok

EMBEDDING:
    
PROMPT_CONFIG:
  trigger_word:
    system_prompt: system_prompt
    input_prompt: input_prompt
  CONTENT_TYPES:
    - Research
  PROMPT_FILES:
    image_summary: prompts/image_summary.txt
    refine_query: prompts/refine_query.txt

REDIS:
  KEY:
    PREFIX: "redis_key_prefix"
    SUFIX: "redis_key_sufix"